name: GitHub Snake Game
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: '${{ github.repository_owner }}'
          outputs: >
            dist/snake.gif?color_snake=#2350A9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: ./dist
          publish_branch: output
          commit_message: 'Update snake animation [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
